<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TeamOrganization.Domain/TeamOrganization.Domain.csproj" />
    <ProjectReference Include="../TeamOrganization.Application/TeamOrganization.Application.csproj" />
  </ItemGroup>

</Project>
